version: '3.7'

services:
  web:
    build: .
    restart: always
    command: python /code/manage.py makemigrations --noinput
    command: python /code/manage.py migrate --noinput
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    build: database/.
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
